k8s_build_namespace: ci
registry:
  port: 5001
  name: local
  user: myuser
  password: mypassword
  service_name: docker-registry-integ
jenkins:
  port: 8080
  service_name: my-jenkins
  m2_settings_secretname: m2-settings
  kube_config_secretname: kube-config
  maven_repo_pvc: maven-repo
nexus: 
  port: 8081
  service_name: my-nexus-repository-manager
postgresql:
  port: 5432
  service_name: my-postgresql
kaniko:
  secret_name: kaniko-secret
flag_undo: false
