- name: Add Nexus helm repo
  kubernetes.core.helm_repository:
      name: sonatype
      repo_url: https://sonatype.github.io/helm3-charts/

- name: Install Nexus Helm Chart
  kubernetes.core.helm:
    name: '{{ nexus.service_name }}'
    namespace: '{{ namespace }}'
    chart_ref: sonatype/nexus-repository-manager
    create_namespace: true
    wait: true

- name: Search for Nexus Pod
  kubernetes.core.k8s_info:
    kind: Pod
    namespace: '{{ namespace }}'
    label_selectors:
      - app.kubernetes.io/name = nexus-repository-manager
      - app.kubernetes.io/instance = {{ nexus.service_name }}
  register: nexus_pod

- name: Get Nexus admin password
  kubernetes.core.k8s_exec:
    namespace: '{{ namespace }}'
    pod: '{{ nexus_pod.resources[0].metadata.name }}'
    command: cat /nexus-data/admin.password
  register: nexus_admin_password

- name: Print Nexus admin password
  debug:
    msg: "Nexus Login: admin, Pwd: {{ nexus_admin_password.stdout }}"

- name: Expose Nexus api port
  shell: >
    nohup kubectl --namespace {{ namespace }} port-forward svc/{{ nexus.service_name }} {{ nexus.port }}:{{ nexus.port }} --address='0.0.0.0' >/dev/null 2>&1 &