# Kind registry and cluster creation

- name: Get infos on container
  docker_container_info:
    name: kind-registry
  register: registry

- name: Registry script
  script:
    cmd: script/kind-with-registry.sh
  register: out
  when: not registry.exists

- debug:
    var: out.stdout
